services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:8.3.3
    container_name: onlyoffice-documentserver
    ports:
      - "8081:80"
    environment:
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=secret
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    volumes:
      - ./app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  
      - ./app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  
      - ./app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice 
      - ./app/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq 
      - ./app/onlyoffice/DocumentServer/redis:/var/lib/redis 
      - ./app/onlyoffice/DocumentServer/db:/var/lib/postgresql
    restart: always
    stdin_open: true