services:
  postgres:
    image: postgres:17.4
    container_name: nextcloud-postgres
    # Ports are not expose due to security reason
    # ports:
    #  - 6379:6379
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  redis:
    image: redis:7.4.2
    container_name: nextcloud-redis
    # Ports are not expose due to security reason
    # ports:
    # - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  app:
    image: nextcloud:31.0.4
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
      - onlyoffice

  cron:
    image: nextcloud:31.0.4
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - postgres
      - redis
      - onlyoffice

  onlyoffice:
    image: onlyoffice/documentserver:8.3.3
    container_name: onlyoffice
    restart: always
    ports:
      - 8081:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=supersecretjwtkey
    #  - JWT_HEADER=Authorization

volumes:
  db_data:
  redis_data:
  nextcloud:
  onlyoffice:
